name = "connes-rigidity"
version = "0.1.0"
keywords = ["math", "formalization"]
defaultTargets = ["Connes", "ComparatorChallenges"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "c2d7843e04aa6cc44fa7e2b39422f24f7b725f00"

[[require]]
name = "Comparator"
git = "https://github.com/leanprover/comparator.git"
rev = "v4.34.0-rc2"

[[require]]
name = "lean4export"
scope = "leanprover"
rev = "v4.34.0-rc2"

[[lean_lib]]
name = "Connes"

[[lean_lib]]
name = "ComparatorChallenges"
roots = ["ComparatorChallenges.F_ConnesZhou"]
