name = "connes-rigidity"
version = "0.1.0"
keywords = ["math", "formalization"]
defaultTargets = ["Connes", "ComparatorChallenges"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "79cba2e8b532ff92484dfd99f45987bae8b2fd7e"

[[require]]
name = "Comparator"
git = "https://github.com/leanprover/comparator.git"
rev = "v4.34.0-rc1"

[[require]]
name = "lean4export"
scope = "leanprover"
rev = "v4.34.0-rc1"

[[lean_lib]]
name = "Connes"

[[lean_lib]]
name = "ComparatorChallenges"
roots = ["ComparatorChallenges.F_ConnesZhou"]
