/-
Copyright 2026 utensil
SPDX-License-Identifier: Apache-2.0

Mechanical transfer of the split-extension ICC proof from
OpenAI/ten-proofs, `ConnesRigidity.lean:31899-31958`, into the Zhou §5
directory. The proof is generic and matches the local CountableDiscreteGroup
and IsICC vocabulary exactly.
-/
import Connes.Core

namespace Connes
namespace OpenAIPort

universe u

/-- Conjugacy orbit generated by a split quotient section. Paper: §5. -/
def splitConjugationOrbit
    (G H : CountableDiscreteGroup.{u}) (section_ : H →* G) (x : G) : Set G :=
  Set.range fun h : H ↦ section_ h * x * (section_ h)⁻¹

/-- ICC transfer across a split quotient with infinite kernel orbits. Paper: §5. -/
theorem isICC_of_split_quotient
    (G H : CountableDiscreteGroup.{u})
    (projection : G →* H) (section_ : H →* G)
    (hsection : ∀ h : H, projection (section_ h) = h)
    (hH : IsICC H)
    (hkernel : ∀ x : G, projection x = 1 → x ≠ 1 →
      (splitConjugationOrbit G H section_ x).Infinite) :
    IsICC G := by
  rcases hH with ⟨hH_infinite, hH_conjugacy⟩
  haveI : Infinite H := hH_infinite
  have hsection_injective : Function.Injective section_ := by
    intro a b hab
    simpa only [hsection] using congrArg projection hab
  refine ⟨Infinite.of_injective section_ hsection_injective, ?_⟩
  intro x hx
  by_cases hprojection : projection x = 1
  · exact (hkernel x hprojection hx).mono (by
      rintro y ⟨h, rfl⟩
      exact ⟨section_ h, rfl⟩)
  · apply Set.Infinite.of_image projection
    apply (hH_conjugacy (projection x) hprojection).mono
    rintro y ⟨h, rfl⟩
    refine ⟨section_ h * x * (section_ h)⁻¹, ⟨section_ h, rfl⟩, ?_⟩
    simp only [map_mul, hsection, map_inv]

/-- Countable discrete semidirect-product group wrapper. Paper: §5. -/
def semidirectCountableGroup
    (A H : CountableDiscreteGroup.{u}) (action : H →* MulAut A) :
    CountableDiscreteGroup.{u} where
  Carrier := SemidirectProduct A H action
  group := inferInstance
  countable := SemidirectProduct.equivProd.injective.countable

/-- ICC transfer for a semidirect product with infinite module orbits. Paper: §5. -/
theorem semidirect_isICC
    (A H : CountableDiscreteGroup.{u}) (action : H →* MulAut A)
    (hH : IsICC H)
    (horbit : ∀ a : A, a ≠ 1 →
      (Set.range fun h : H ↦ action h a).Infinite) :
    IsICC (semidirectCountableGroup A H action) := by
  apply isICC_of_split_quotient
    (semidirectCountableGroup A H action) H
    SemidirectProduct.rightHom SemidirectProduct.inr
    (fun h ↦ SemidirectProduct.rightHom_inr h) hH
  intro x hright hx
  change x.right = 1 at hright
  have hleft : x.left ≠ 1 := by
    intro hleft
    apply hx
    apply SemidirectProduct.ext
    · exact hleft
    · exact hright
  have hinfinite :
      ((SemidirectProduct.inl (φ := action) : A →* SemidirectProduct A H action) ''
        (Set.range fun h : H ↦ action h x.left)).Infinite :=
    (horbit x.left hleft).image
      (SemidirectProduct.inl_injective (φ := action)).injOn
  apply hinfinite.mono
  rintro y ⟨a, ⟨h, rfl⟩, rfl⟩
  refine ⟨h, ?_⟩
  have hxkernel : x = SemidirectProduct.inl x.left := by
    apply SemidirectProduct.ext
    · rfl
    · simpa only [SemidirectProduct.right_inl] using hright
  rw [hxkernel]
  apply SemidirectProduct.ext
  · change
      (1 * action h x.left) * action (h * 1) (action h⁻¹ 1⁻¹) =
        action h x.left
    simp only [one_mul, mul_one, map_inv, inv_one, map_one]
  · change (h * 1) * h⁻¹ = 1
    simp only [mul_one, mul_inv_cancel]

end OpenAIPort
end Connes
