/-
Copyright 2026 utensil
SPDX-License-Identifier: Apache-2.0

Derived in part from Apache-2.0 `openai/ten-proofs`, `ConnesRigidity.lean` at
94bc0feb6a9ff12c7d31d6de640a725c9d43d2b6, lines 35870-35940.
Modifications: extracted the double-centralizer generator reduction, added a
local conjugacy helper, and changed namespace. Paper: §3. See docs/PORT_MAP.md.
-/
import Mathlib
import Connes.Core

namespace Connes

noncomputable section

open scoped ENNReal

/- A unitary conjugation carries a double-centralizer closure along with its
generating set. Paper: §3. -/
theorem mem_vonNeumannClosure_iff_of_conj_image_eq
    {H J : Type*}
    [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]
    [NormedAddCommGroup J] [InnerProductSpace ℂ J] [CompleteSpace J]
    (U : H ≃ₗᵢ[ℂ] J)
    (S : Set (H →L[ℂ] H)) (T : Set (J →L[ℂ] J))
    (hST : U.conjStarAlgEquiv '' S = T)
    (x : H →L[ℂ] H) :
    x ∈ vonNeumannClosure S ↔
      U.conjStarAlgEquiv x ∈ vonNeumannClosure T := by
  let e := U.conjStarAlgEquiv
  have hST' : e '' S = T := by
    simpa [e] using hST
  have hback : ∀ z, z ∈ StarSubalgebra.centralizer ℂ T →
      e.symm z ∈ StarSubalgebra.centralizer ℂ S := by
    intro z hz
    simp only [StarSubalgebra.mem_centralizer_iff] at hz ⊢
    intro y hy
    have hey : e y ∈ T := by
      rw [← hST']
      exact ⟨y, hy, rfl⟩
    obtain ⟨hcomm, hstar⟩ := hz (e y) hey
    constructor
    · simpa only [map_mul e.symm, StarAlgEquiv.symm_apply_apply] using
        congrArg e.symm hcomm
    · simpa only [map_mul e.symm, map_star e.symm,
        StarAlgEquiv.symm_apply_apply] using
        congrArg e.symm hstar
  have hforward : ∀ z, z ∈ StarSubalgebra.centralizer ℂ S →
      e z ∈ StarSubalgebra.centralizer ℂ T := by
    intro z hz
    simp only [StarSubalgebra.mem_centralizer_iff] at hz ⊢
    intro y hy
    rw [← hST'] at hy
    obtain ⟨x', hx', rfl⟩ := hy
    obtain ⟨hcomm, hstar⟩ := hz x' hx'
    constructor
    · simpa only [map_mul e, StarAlgEquiv.apply_symm_apply] using
        congrArg e hcomm
    · simpa only [map_mul e, map_star e, StarAlgEquiv.apply_symm_apply] using
        congrArg e hstar
  constructor
  · intro hx
    change e x ∈ vonNeumannClosure T
    rw [mem_vonNeumannClosure] at hx ⊢
    simp only [StarSubalgebra.mem_centralizer_iff] at hx ⊢
    intro z hz
    obtain ⟨hcomm, hstar⟩ := hx (e.symm z) (hback z hz)
    constructor
    · simpa only [map_mul e, StarAlgEquiv.apply_symm_apply] using
        congrArg e hcomm
    · simpa only [map_mul e, map_star e, StarAlgEquiv.apply_symm_apply] using
        congrArg e hstar
  · intro hx
    change e x ∈ vonNeumannClosure T at hx
    rw [mem_vonNeumannClosure] at hx ⊢
    simp only [StarSubalgebra.mem_centralizer_iff] at hx ⊢
    intro z hz
    obtain ⟨hcomm, hstar⟩ := hx (e z) (hforward z hz)
    constructor
    · simpa only [map_mul e.symm, StarAlgEquiv.symm_apply_apply] using
        congrArg e.symm hcomm
    · simpa only [map_mul e.symm, map_star e.symm,
        StarAlgEquiv.symm_apply_apply] using
        congrArg e.symm hstar

/- The double-centralizer closure is unchanged when a factor is generated by
products of a smaller generating family. Paper: §3. -/
theorem vonNeumannClosure_eq_of_factor_generators
    {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H]
    [CompleteSpace H]
    (S T : Set (H →L[ℂ] H))
    (hsub : T ⊆ S)
    (hfactor : ∀ x ∈ S, ∃ a ∈ T, ∃ b ∈ T, x = a * b) :
    vonNeumannClosure S = vonNeumannClosure T := by
  have hcent : StarSubalgebra.centralizer ℂ S =
      StarSubalgebra.centralizer ℂ T := by
    ext z
    simp only [StarSubalgebra.mem_centralizer_iff]
    constructor
    · intro hz x hx
      exact hz x (hsub hx)
    · intro hz x hx
      obtain ⟨a, ha, b, hb, rfl⟩ := hfactor x hx
      obtain ⟨ha₀, ha₁⟩ := hz a ha
      obtain ⟨hb₀, hb₁⟩ := hz b hb
      constructor
      · calc
          (a * b) * z = a * (b * z) := by rw [mul_assoc]
          _ = a * (z * b) := by rw [hb₀]
          _ = (a * z) * b := by rw [mul_assoc]
          _ = (z * a) * b := by rw [ha₀]
          _ = z * (a * b) := by rw [mul_assoc]
      · rw [star_mul]
        calc
          (star b * star a) * z = star b * (star a * z) := by rw [mul_assoc]
          _ = star b * (z * star a) := by rw [ha₁]
          _ = (star b * z) * star a := by rw [mul_assoc]
          _ = (z * star b) * star a := by rw [hb₁]
          _ = z * (star b * star a) := by rw [mul_assoc]
  apply SetLike.coe_injective
  rw [coe_vonNeumannClosure, coe_vonNeumannClosure, hcent]

/- The regular factor of a semidirect product is generated by its two
subgroup embeddings. Paper: §3. -/
theorem semidirect_vonNeumannClosure_eq_inl_inr
    {A K : Type*} [Group A] [Group K] (φ : K →* MulAut A) :
    vonNeumannClosure
      (Set.range fun x : A ⋊[φ] K =>
        (leftRegularRepresentation (A ⋊[φ] K) x :
          GroupL2 (A ⋊[φ] K) →L[ℂ] GroupL2 (A ⋊[φ] K))) =
      vonNeumannClosure
        ((Set.range fun a : A =>
          (leftRegularRepresentation (A ⋊[φ] K)
            (SemidirectProduct.inl a) :
            GroupL2 (A ⋊[φ] K) →L[ℂ] GroupL2 (A ⋊[φ] K))) ∪
        (Set.range fun k : K =>
          (leftRegularRepresentation (A ⋊[φ] K)
            (SemidirectProduct.inr k) :
            GroupL2 (A ⋊[φ] K) →L[ℂ] GroupL2 (A ⋊[φ] K)))) := by
  apply vonNeumannClosure_eq_of_factor_generators
  · rintro _ (⟨a, rfl⟩ | ⟨k, rfl⟩)
    · exact ⟨SemidirectProduct.inl a, rfl⟩
    · exact ⟨SemidirectProduct.inr k, rfl⟩
  · rintro _ ⟨g, rfl⟩
    refine ⟨(leftRegularRepresentation (A ⋊[φ] K)
        (SemidirectProduct.inl g.left) :
        GroupL2 (A ⋊[φ] K) →L[ℂ] GroupL2 (A ⋊[φ] K)),
      Or.inl ⟨g.left, rfl⟩,
      (leftRegularRepresentation (A ⋊[φ] K)
        (SemidirectProduct.inr g.right) :
        GroupL2 (A ⋊[φ] K) →L[ℂ] GroupL2 (A ⋊[φ] K)),
      Or.inr ⟨g.right, rfl⟩, ?_⟩
    change
      (leftRegularRepresentation (A ⋊[φ] K) g :
        GroupL2 (A ⋊[φ] K) →L[ℂ] GroupL2 (A ⋊[φ] K)) = _
    conv_lhs =>
      rw [← SemidirectProduct.inl_left_mul_inr_right g]
    rw [map_mul (leftRegularRepresentation (A ⋊[φ] K))]
    rfl

end
end Connes
